add deault snippet to google search results
KeyError: 'snippet' would cause an exception in web_search with the google provider. -modified google_search_provider to to use item.get('snippet') to prevent KeyError